from drf_crud_backend.settings.config import *

CELERY_BROKER_URL = CELERY_BROKER_URL  # URL Redis-сервера
CELERY_RESULT_BACKEND = CELERY_RESULT_BACKEND  # URL Redis-сервера для хранения результатов задач
CELERY_ACCEPT_CONTENT = CELERY_ACCEPT_CONTENT
CELERY_TASK_SERIALIZER = CELERY_TASK_SERIALIZER
CELERY_RESULT_SERIALIZER = CELERY_RESULT_SERIALIZER