import os

if os.environ.get('DJANGO_DEVELOPMENT') is not None:
    from drf_crud_backend.settings.prod_settings import *
else:
    from drf_crud_backend.settings.local_settings import *

DEBUG = DEBUG

CELERY_BROKER_URL = CELERY_BROKER_URL
CELERY_RESULT_BACKEND = CELERY_RESULT_BACKEND
CELERY_ACCEPT_CONTENT = CELERY_ACCEPT_CONTENT
CELERY_TASK_SERIALIZER = CELERY_TASK_SERIALIZER
CELERY_RESULT_SERIALIZER = CELERY_RESULT_SERIALIZER

DB_ENGINE = DB_ENGINE
DB_NAME = DB_NAME
DB_USER = DB_USER
DB_PASSWORD = DB_PASSWORD
DB_HOST = DB_HOST
DB_PORT = DB_PORT

SECRET_KEY = SECRET_KEY
API_VERSION = API_VERSION

EMAIL_BACKEND = EMAIL_BACKEND
EMAIL_HOST = EMAIL_HOST
EMAIL_PORT = EMAIL_PORT
EMAIL_USE_TLS = EMAIL_USE_TLS
EMAIL_USE_SSL = EMAIL_USE_SSL
EMAIL_HOST_USER = EMAIL_HOST_USER
EMAIL_HOST_PASSWORD = EMAIL_HOST_PASSWORD
DEFAULT_FROM_EMAIL = DEFAULT_FROM_EMAIL
